### ISSUE TITLE
theme watch --notify not notifying

### ISSUE THREAD

**Issue by derekmorash** [Shopify/themekit#267]
I'm trying to get theme watch to notify my browsersync instance, however whenever a file is changed and uploaded it doesn't notify the file I specify (theme watch --notify=/tmp/theme.update). The file doesn't even get created. I've tried giving it a different file and directory, but it still does nothing.

Watch works perfectly, uploads the file just as it should, but notify does nothing. Am I doing it wrong or am I misinterpreting what notify does? I can't find anything on notify other than the docs.

**Comment by tanema** [comment]
hey @derekmorash it seems in a previous refactor, the notify file functionality was broken. I will look into it.

**Comment by cameronroe** [comment]
I had the same issue. To be honest, I don't think the flag makes that much sense. Will pick up discussion on other issues.

**Comment by tanema** [comment]
@cameronroe This issue was solved. If you want to use it please use the command `theme watch --notify=mynotify.tmp` This file will be touched when watch become idle.

**Comment by tanema** [comment]
I might add all of this is in the documentation http://shopify.github.io/themekit/commands/#watch That is what it is there for.

**Comment by derekmorash** [comment]
It's been working great for my team and I, we use it everyday to notify gulp/browsersync. Currently writing a blog post about our process and how we use it. Priceless feature!

**Comment by tanema** [comment]
@derekmorash awesome! I would love it if you sent me a link when you are finished!

**Comment by dviedma** [comment]
sorry this is still broken for me. i realized some time has gone by but...is it working for everybody else?
