### ISSUE TITLE
Theme Watch triggering for all image files in /assets

### ISSUE THREAD

**Issue by samjross** [Shopify/themekit#519]
### What happened
When I do `theme watch` lately, it will usually run as expected for 10-30 minutes, until eventually it perceives all the images files in /assets as having been updated, and starts trying to upload them all.

### What I expected to happen
Only upload files when they're actually changed.

### Steps to reproduce

1. Theme watch
2. Work on theme for about half an hour as normal
3. Observe in the command line, "Received Update event on assets/img.png" for every image in the assets folder

### My Environment

OS (including version): Windows 10 v 1803
Themekit version: 0.7.5
Ignore Files(if any):

**Comment by tanema** [comment]
Do you have any software on your computer that may be scanning files? I have a suspicion that it may be a virus scanner but I can't be certain. I would normally say to ignore image files anyways because they don't need to be watched while you are developing your site.

**Comment by samjross** [comment]
how do i ignore image files?

**Comment by tanema** [comment]
There are some examples in the documentation https://shopify.github.io/themekit/ignores/#ignores-in-configyml-example

**Comment by tanema** [comment]
@samjross have you had any further problems with this?

**Comment by tanema** [comment]
Closing because this issue seems to have been solved.

**Comment by samjross** [comment]
It actually hasn't stopped doing it, but it's not specifically image files as I initially thought. It looks like it's just all files, or maybe just all files in /assets/. I thought it was just images because I have mostly images there.

When it happens I can't even press ctrl+c to stop the process, it just continues until I close the console.

Still happening with most recent update of theme kit

**Comment by tanema** [comment]
What is your editor? themekit uses windows ReadDirectoryChangesW functionality in the background, which is really well integrated with windows so there really should not be any fluke events. Something is touching either your files or the directory itself.

**Comment by samjross** [comment]
I'm using sublime text 3

**Comment by tanema** [comment]
Okay some extra questions that may help

- Are you running themekit in cmd.exe or powershell or something else?
- Do you have your files on your main harddrive or are they on an external drive?
- Do you leave themekit running for days at a time?
- Is it only the asset folder or are templates being uploaded as well?

**Comment by ikolarov** [comment]
Hi tanema.

> Are you running themekit in cmd.exe or powershell or something else?

Running it under Cmder ( which use ConEmu ) configured for use of GitBash. Or to cut it short - GitBash,

> Do you have your files on your main harddrive or are they on an external drive?

They are on the main hard drive, but not in the "C:" drive but at my "D:" drive.

> Do you leave themekit running for days at a time?

No, the PC is turned of every day and I switch between different projects every day, so it's not on for more than 3-4 hours a day ( max 8 hours if there is a big project ).

> Is it only the asset folder or are templates being uploaded as well?

No its everything and it's randomly some times, I mean that it uploads different files from different folder one after another.

Here is a video of the issue when it happens for me: https://streamable.com/8wwx3 ( please note that because of NDA can't show the full console with the store name, that's why it's cropped )

**Comment by tanema** [comment]
Another report of this from @besteven

with the environment:
 - OS [e.g. iOS]: Window 10
- Themekit version [e.g. v0.7.5]: v0.8.1 (the lastest version)
 - Editor [e.g. atom, sublime]: VS Code
 - Ignore: None

**Comment by tanema** [comment]
This seems to be specifically an issue with windows 10 events. I will get access to a windows 10 computer soon to test this.

**Comment by tanema** [comment]
Okay! I have been able to reproduce this on windows 10 only.

**Comment by tanema** [comment]
Okay I can confirm that it is because windows 10 fires write events if even any of the timestamps change, including last_viewed. This makes it complicated to fix because now I need to add in more complicated checks to make sure that the file contents have actually changed. I will be in contact about any progress made on this.

**Comment by tanema** [comment]
@ikolarov @samjross @besteven 
Please try out this version with an updated fix for windows file watching by running:
`theme update --version=v1.0.0-issue519`

This is a special version of the pre-release themekit with a new filewatcher. Please give it a try and report if it has fixed your issues and if you experience any other bugs with it.

**Comment by ikolarov** [comment]
@tanema from what I can see it works OK for me now. There was a single instance where the watch froze and stop updating but this was a single instance and couldn't reproduce the issue a second time.

It seems that the issue is fixed on my end, we will install it on all the PC's here and see if any other have issues with it.

Thank you for the support @tanema!

**Comment by tanema** [comment]
Okay this has been merged into master so it will be on the prerelease. 

Please use the prerelease going forward and open any issues for the prerelease.

You can update to the prerelease by running `theme update --version=v1.0.0-pre`
